package client;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import server.Request;

import java.io.*;
import java.net.*;

public class Client {
  public void go() {
    System.out.println("Client connected");
    Request request = new Request();

    try {
      Socket socket = new Socket("127.0.0.1", 3000);
      while (true) {
        PrintStream out = new PrintStream(socket.getOutputStream());
        BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
        out.write(((request.request("GET","/echo")).getBytes("UTF-8")));
        String line = in.readLine();

        while (line != null) {
          System.out.println(line);
          line = in.readLine();
        }
        in.close();
        out.close();
        socket.close();
      }
    } catch (IOException ex) {
      System.out.println("Ooops failed connection");
      ex.printStackTrace();
    }
  }

  public static void main(String[] args) {
    Client client = new Client();
    client.go();
  }
}
