package client;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import Request.Request;

import java.io.*;
import java.net.*;

public class Client {
  private PrintWriter out;
  private BufferedReader in;
  private Socket socket;
  private int PORT = 3000;

  public Client() throws IOException {
    socket = createSocket();
    out = new PrintWriter(socket.getOutputStream());
    in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
  }

  public void go() throws IOException {
    System.out.println("Client connected");
    while (true) {
      makeRequest(out, new Request().requestPost("goodbye"));
      readResponse(in);
      in.close();
      out.close();
      socket.close();
      System.out.println("Connection closed");
    }
  }

  private void readResponse(BufferedReader in) {
    try {
      System.out.print(in.read());
//      String line;
//      while ((line = in.readLine()) != null) {
//        System.out.println(line);
//       }
      System.out.println("I got here");

    } catch (IOException ex) {
      System.out.println(ex);
      System.out.println("Read failed");
      System.exit(-1);
    }
  }

  public void makeRequest(PrintWriter out, String request) throws IOException {
    out.write((request));
    out.flush();
  }

  public Socket createSocket() {
    Socket socket = null;
    try {
      socket = new Socket("127.0.0.1", PORT);
    } catch (IOException ex) {
      System.out.println("Could not listen on port " + PORT);
      ex.printStackTrace();
      System.exit(-1);
    }
    return socket;
  }

  public static void main(String[] args) throws IOException {
    new Client().go();
  }
}
