package client;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import Request.Request;

import java.io.*;
import java.net.*;
import java.nio.channels.Channel;

public class Client {
  private PrintStream out;
  private BufferedReader in;
  private Socket socket;
  private int PORT = 3000;

  public Client() throws IOException {
    socket = createSocket();
    out = new PrintStream(socket.getOutputStream());
    in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
  }

  public void go() throws IOException {
    System.out.println("Client connected");
    while (true) {
      makeRequest(out);
      readResponse(in);
      in.close();
      out.close();
      socket.close();
      System.out.println("Connection closed");
    }
  }

  private void readResponse(BufferedReader in) {
    try {
      String line = in.readLine();
      while (line != null) {
        System.out.println(line);
        line = in.readLine();
      }
    } catch (IOException ex) {
      System.out.println(ex);
      System.out.println("Read failed");
      System.exit(-1);
    }
  }

  public void makeRequest(PrintStream out) {
    Request request = new Request();
    try {
//    out.write(((request.requestGet("GET","/echo")).getBytes("UTF-8")));
      out.write(((request.requestPost("POST", "/echo", "say=Hi&to=Mom")).getBytes("UTF-8")));
      out.flush();
    } catch (IOException ex) {
      System.out.println(ex);
      System.out.println("Read failed");
      System.exit(-1);
    }
  }

  public Socket createSocket() {
    Socket socket = null;
    try {
      socket = new Socket("127.0.0.1", PORT);
    } catch (IOException ex) {
      System.out.println("Could not listen on port " + PORT);
      ex.printStackTrace();
      System.exit(-1);
    }
    return socket;
  }

  public static void main(String[] args) throws IOException {
    new Client().go();
  }
}
