package client;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.*;
import java.net.*;

public class HelloWorldClient {
  public void go() {
    System.out.println("Client connected --- ");

    try {
      Socket socket = new Socket("127.0.0.1", 3000);

      InputStreamReader streamReader = new InputStreamReader(socket.getInputStream());
//            System.out.println(streamReader);

      BufferedReader reader = new BufferedReader(streamReader);
      String line;
      while ((line = reader.readLine()) != null) {
        System.out.println("hetr");
        System.out.println(line);
        System.out.println("ther");
      }

//            String something = reader.readLine();
//            System.out.println(something);

      reader.close();
    } catch (IOException ex) {
      ex.printStackTrace();
    }
  }
}
