package client;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.*;
import java.net.*;

public class HelloWorldClient {
    public void go() {
        try {
            Socket socket = new Socket("127.0.0.1", 3000);
            System.out.println("Client connected --- ");

            InputStreamReader streamReader = new InputStreamReader(socket.getInputStream());
            BufferedReader reader = new BufferedReader(streamReader);

            String something = reader.readLine();
            System.out.println(something);
            System.out.println("Client connected");

            reader.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}
