package server;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.*;
import java.net.*;
import java.io.File;

public class HelloWorldServer {
    public void go() {
        try {
            ServerSocket serverSock = new ServerSocket(3000);

            while(true) {
                Socket socket = serverSock.accept();
                System.out.println("got a request");
                InputStream inputStream = socket.getInputStream();
                OutputStream outputStream = socket.getOutputStream();

                String htmlContent = getHtmlContent("hello-world.html");
                String headers = setHeaders(htmlContent);

                outputStream.write((headers + htmlContent).getBytes("UTF-8"));
                outputStream.flush();
                socket.close();
            }
        } catch(IOException ex) {
            ex.printStackTrace();
        }
    }

    public String getHtmlContent(String filename) {
        String response = "";
        try {
            File helloWorld = new File(filename);
            BufferedReader reader = new BufferedReader(new FileReader(helloWorld));
            String line;
            try {
                while ((line = reader.readLine()) != null) {
                    response += line;
                }
            } catch(IOException ex) {
                ex.printStackTrace();
            }
        } catch(FileNotFoundException exception) {
            System.out.println(exception);
        }
        return response;
    }

    public String setHeaders(String content) {
        String headers = "HTTP/1.1 200 OK\r\n" + "Content-Length: " + content.length() + "\r\n" + "Content-Type: text/html\r\n\r\n";
        return headers;
    }
}
