package testClient;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import Response.Status200;

import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;

public class TestClient {
  private Socket socket;
  private PrintWriter out;
  private BufferedReader in;

  public TestClient() throws IOException {
    this.socket = new Socket("127.0.0.1", 3000);
//    this.out = new PrintWriter(new OutputStreamWriter(socket.getOutputStream()));
//    this.in = new BufferedReader(new InputStreamReader(socket.getInputStream(), StandardCharsets.UTF_8));
  }

  public void sendRequest(String request) throws IOException {
//    Send request must not be sending if it is only failing for test client
    PrintWriter out = new PrintWriter(new OutputStreamWriter(socket.getOutputStream()));
    out.write(request);
    out.flush();
  }

  public String getResponse() throws IOException {
    BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream(), StandardCharsets.UTF_8));

    StringBuilder responseBuilder = new StringBuilder();

    while (in.ready() || responseBuilder.length() == 0) {
      responseBuilder.append((char) in.read());
    }
    return responseBuilder.toString();
  }

  public void closeSocket() throws IOException {
    in.close();
    out.close();
    socket.close();
  }
}
