/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import server.HelloWorldServer;
import client.HelloWorldClient;


public class App {
    public static void main(String[] args) {
        HelloWorldServer server = new HelloWorldServer();
        server.go();
        HelloWorldClient client = new HelloWorldClient();
        client.go();
    }
}
